// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BBeIfvNXszb3QDxFctsuUl3s82ps-a4',
    appId: '1:746647090999:web:2a64908593678787ceccb2',
    messagingSenderId: '746647090999',
    projectId: 'notes-ai-aa5da',
    authDomain: 'notes-ai-aa5da.firebaseapp.com',
    storageBucket: 'notes-ai-aa5da.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyklom5K2P7rPdfRIkVUO60JFdm47seRU',
    appId: '1:746647090999:ios:65f8967bc50e9f4cceccb2',
    messagingSenderId: '746647090999',
    projectId: 'notes-ai-aa5da',
    storageBucket: 'notes-ai-aa5da.firebasestorage.app',
    iosBundleId: 'com.example.noteDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-BBeIfvNXszb3QDxFctsuUl3s82ps-a4',
    appId: '1:746647090999:web:ae4d062d288a6b69ceccb2',
    messagingSenderId: '746647090999',
    projectId: 'notes-ai-aa5da',
    authDomain: 'notes-ai-aa5da.firebaseapp.com',
    storageBucket: 'notes-ai-aa5da.firebasestorage.app',
  );
}
