name: Build Flutter

on:
  push:
    branches: ["release"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos
            output: build/macos/Build/Products/Release/*.app
          - os: windows-latest
            platform: windows
            output: build/windows/x64/runner/Release/

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x
      - run: flutter --version ; dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Run build runner
        run: dart run build_runner build

      - name: Write config
        run: echo '${{ secrets.CONFIG_JSON }}' > config.json

      - name: Build
        run: flutter build ${{ matrix.platform }} --release --dart-define-from-file=config.json  --dart-define=ENVIRONMENT=TEST

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: ${{ matrix.output }}
